spring:
  profiles:
    active: local
  application:
    name: demo-cube
  main:
    allow-bean-definition-overriding: true
app:
  id: demo-cube
management:
  endpoints:
    web:
      exposure:
        include: startup
